### ISSUE TITLE
补充第44条。

### ISSUE THREAD

**Issue by ttepier** [Justicedeveloper/Justicedeveloper#5]
最近出了个培训考试，考不过直接待岗一个月，工资调为2000。一个月后再次考试

**Comment by ttepier** [comment]
> 最近出了个培训考试，考不过直接待岗一个月，工资调为2000。一个月后再次考试

**Comment by Justicedeveloper** [comment]
已经添加

**Comment by mzy0318** [comment]
河南喔轩网络科技有限公司和河南星矢网络科技有限公司，公司实际运营控制人都是武越林，拖欠员工工资，也只有员工到他的新公司（河南品驰网络科技有限公司）上班才会支付在上两家公司工作的工资。而且还是分期支付，已经向法院起诉

**Comment by Justicedeveloper** [comment]
已添加

**Comment by Justicedeveloper** [comment]
> 最近出了个培训考试，考不过直接待岗一个月，工资调为2000。一个月后再次考试
