### ISSUE TITLE
其他城市的推荐和不推荐列表

### ISSUE THREAD

**Issue by chordw** [Justicedeveloper/Justicedeveloper#6]
首先感谢这个库给我带来的帮助。
如题，有没有其他城市的类似的列表，或者相关项目的地址链接。关联一下让更多人受益，望采纳！

**Comment by Justicedeveloper** [comment]
各省统计文档地址：https://docs.qq.com/sheet/DV3JRR0VGRlZBZXJK?newPad=1&newPadType=clone&tab=w175tl

**Comment by Justicedeveloper** [comment]
> 首先感谢这个库给我带来的帮助。
> 如题，有没有其他城市的类似的列表，或者相关项目的地址链接。关联一下让更多人受益，望采纳！
